spring:
  application:
    name: gymapp-workload-service
  cloud:
    config:
      enabled: false
  config:
    import: ""        # prevents Spring from calling Config Server
  data:
    mongodb:
      database: trainers_training_duration
  mongodb:
    embedded:
      version: 6.0.5  # pick a version supported by flapdoodle
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useJmx=false

jwt:
  secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
  expirationTime: 3600000

eureka:
  client:
    enabled: false

server:
  port: 8081

logging:
  level:
    root: INFO